### PR TITLE
Adding Test Case 01 Data Sets

### PR DESCRIPTION
**Pull request by nutterb**
Files for a cross-sectional, single center, form, single arm project.

How'd I do?  Are all the files there that we want?

### CODE REVIEW

**Comment by wibeasley** [comment]
Thanks for the files, @nutterb.  I have a few questions and requests.  And I like your md doc.
1. So we keep the (file & directory) naming scheme consistent, can you use all lower case with dashes separating the words?  For example `SampleProjects/TEST-CASE-01/DataDictionary.csv` would be changed to `sample-projects/test-case-01/data-dictionary.csv`.
2. I'd like to keep these datasets as language-agnostic as possible.  Can you explain the purpose of the DESCRIPTION file?  I wasn't thinking of submitting this to CRAN, but I'd like to hear your thoughts.
3. I was planning for each dataset to live in the root directory, instead of something like the `SampleProjects/` you put yours in.  The [knitr examples](https://github.com/yihui/knitr-examples) repo was a good goal in my opinion.
   
   But I'm open to the idea of nesting the projects in another folder.  What do you see as the advantages?  I assume you were thinking of non-datasets being saved in the `redcap-test-datasets` repo.  Did anything specific come to your mind?

**Comment by nutterb** [comment]
Very helpful comments, @wibeasley.  
1. Yes.  I'll modify the naming scheme tonight and resubmit.
2. The DESCRIPTION file was just what I happened to upload into my test database.  I just pulled it out and dumped it into the repo without giving it much thought (I might have been a little punch drunk from being up past my bedtime).  I'll replace it with better example and include something in the README.
3. Sounds messy to me (I have an irrational fear of long lists), but reasonable.  I'll make these changes tonight.

On my way to work this morning, it also occurred to me that we may want to consider, at some point, requiring the Project Information download.  Since REDCap 6.11.0 allows projects to be created via the API, having the files available will be useful for automating tests in the future.  For longitudinal projects, that would also mean the events, arms, and event-form mappings (importing users probably doesn't make much sense in this case).  I'll start moving these requirements into the repo README for future reference.

**Comment by wibeasley** [comment]
I love that suggestion about using the API to create the projects.  We haven't upgraded yet, so I'm not sure how the other pieces of information (eg, events & arms) should be stored.

If there are groupings of projects you're considering (to reduce the number of projects living at the root level), I'm open to that.

**Comment by thomasnwilson** [comment]
@wibeasley 

Not sure why I'm getting notifications for this project, but I wanted to remind you that our development instance has the API project creation capabilities.  It was upgraded on 2/10/16.  It is available for you to begin testing if you are at the stage.

Our production instance will be upgraded in the next few weeks (as soon as I can free up some time on my schedule).

**Comment by wibeasley** [comment]
Thanks @thomasnwilson, I didn't know our dev box is updated.  Thanks for doing that.

I'm guessing you're getting notifications because I started this repo in our GitHub organization, before I moved it to 'redcap-tools'?  I guess the email system wanted to make sure you felt included.  You know, it's merely trying to maintain a friendship after it split and moved on.  But you're just so stubborn and keep putting up these emotional road blocks, which hurts the feelings of the automated email system.

**Comment by thomasnwilson** [comment]
Sorry github...I'm emotionally unavailable.  It's not you, it's me.

**Comment by nutterb** [comment]
It's nice to confirm that this is a serious place of serious business :)

I've made the desired changes to the pull request.  Let me know if that's a good approximation of what we're after.

**Comment by wibeasley** [comment]
Thanks, @nutterb.

**Comment by wibeasley** [comment]
> Sounds messy to me (I have an irrational fear of long lists), but reasonable. I'll make these changes tonight.

Sorry @nutterb, I wasn't clear.  I think that each project should be in it's own folder in root (like `archer/` is now).  I made a few changes that I think will help address the fear of long lists.  Tell me if there's something you'd like to change.

**Comment by nutterb** [comment]
I _like_ it. A list that fits on my screen :)

**Pull request merged**
